# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/387c11e0-7678-4024-9f67-e2812cbf5686";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/a87cc5b7-9906-4760-8c6c-b22d5512d7b6";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/387c11e0-7678-4024-9f67-e2812cbf5686";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/387c11e0-7678-4024-9f67-e2812cbf5686";
      fsType = "btrfs";
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/387c11e0-7678-4024-9f67-e2812cbf5686";
      fsType = "btrfs";
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/387c11e0-7678-4024-9f67-e2812cbf5686";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/72A4-1CA5";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp109s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
